# Generated by Django 2.0.8 on 2018-09-15 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date_time', models.DateTimeField(null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=10, null=True)),
                ('zip_code', models.CharField(max_length=10, null=True)),
                ('coordinates', models.CharField(max_length=100, null=True)),
                ('victim_name', models.CharField(max_length=200, null=True)),
                ('victim_gender', models.CharField(max_length=10, null=True)),
                ('victim_age', models.IntegerField(null=True)),
                ('motorist_name', models.CharField(max_length=200, null=True)),
                ('motorist_gender', models.CharField(max_length=10, null=True)),
                ('motorist_age', models.IntegerField(null=True)),
                ('hit_and_run', models.NullBooleanField()),
                ('impaired_driving', models.NullBooleanField()),
                ('incident_type', models.CharField(max_length=100, null=True)),
                ('vehicle_type', models.CharField(max_length=100, null=True)),
                ('vehicle_make', models.CharField(max_length=100, null=True)),
                ('vehicle_model', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300, null=True)),
                ('site_name', models.CharField(max_length=200, null=True)),
                ('domain', models.CharField(max_length=300, null=True)),
                ('article_title', models.TextField(null=True)),
                ('article_text', models.TextField(null=True)),
                ('is_related', models.NullBooleanField()),
                ('is_not_USA', models.NullBooleanField()),
                ('Incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidents.Incident')),
            ],
        ),
    ]
