# Generated by Django 2.0.8 on 2018-09-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RunDateTime', models.DateTimeField(null=True)),
                ('NumCandidates', models.IntegerField(null=True)),
                ('NumRelatedCandidates', models.IntegerField(null=True)),
                ('ScrubType', models.CharField(max_length=100, null=True)),
                ('ScrubTypeId', models.IntegerField(null=True)),
                ('SearchKeywords', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
