# Generated by Django 2.0.8 on 2018-09-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_scrub'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentsource',
            name='is_reviewed',
            field=models.NullBooleanField(),
        ),
    ]
