# Generated by Django 2.0.8 on 2018-09-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_incidentsource_is_reviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrub',
            old_name='NumCandidates',
            new_name='candidates',
        ),
        migrations.RenameField(
            model_name='scrub',
            old_name='NumRelatedCandidates',
            new_name='related_candidates',
        ),
        migrations.RenameField(
            model_name='scrub',
            old_name='RunDateTime',
            new_name='run_date_time',
        ),
        migrations.RenameField(
            model_name='scrub',
            old_name='ScrubTypeId',
            new_name='scrub_tpye_id',
        ),
        migrations.RenameField(
            model_name='scrub',
            old_name='ScrubType',
            new_name='scrub_type',
        ),
        migrations.RenameField(
            model_name='scrub',
            old_name='SearchKeywords',
            new_name='search_keywords',
        ),
    ]
