# Generated by Django 2.0.8 on 2018-09-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_auto_20180922_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrub',
            old_name='scrub_tpye_id',
            new_name='scrub_type_id',
        ),
    ]
