# Generated by Django 2.0.8 on 2018-09-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_auto_20180922_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentsource',
            name='source_candidate_id',
            field=models.IntegerField(null=True),
        ),
    ]
