# Generated by Django 2.0.8 on 2019-09-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_auto_20190916_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrub',
            name='run_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
