# Generated by Django 2.0.8 on 2019-09-19 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_scrub_run_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrub',
            name='run_text',
        ),
    ]
