# Generated by Django 2.0.8 on 2019-09-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_remove_scrub_run_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_date_time', models.DateTimeField(null=True)),
                ('error_code', models.IntegerField(null=True)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('error_text', models.TextField(blank=True, null=True)),
                ('associated_url', models.CharField(max_length=300, null=True)),
                ('associated_source_candidate_id', models.IntegerField(null=True)),
            ],
        ),
    ]
