# Generated by Django 2.0.8 on 2019-09-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0011_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='call_stack',
            field=models.TextField(blank=True, null=True),
        ),
    ]
