# Generated by Django 2.0.8 on 2019-09-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0012_error_call_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='associated_scrub_id',
            field=models.IntegerField(null=True),
        ),
    ]
